### ISSUE TITLE
Zander Zulu

### ISSUE THREAD

**Issue by jonathonmcmurray** [AquaqProdSupport1/TorQ#5]
Hi All,

I am expecting a large increase in data throughput of my tick/ data captire system over the next two weeks. I will not get a chance to do a major release to deal with this increase in message rate. What short term stems, ( along with reasons why) can I take in the short term to deal with this? Im open to any suggestions as I am desperate at the moment.

[ Id like a really comprehensive answer from each team please by tomorrow at 10AM. ]

Regards,

Zander Zulu

**Comment by JedwardsEdwards** [comment]
Hi Zander,

If you're expecting a large increase in data throughput there are two main ways you can support your system: you can make a number of minor changes to your active capture system as it currently stands, and you can plan for disaster recovery.

Regarding changes to your active system, the first thing you can do is set up your tickerplant to run in batch mode as opposed to zero latency mode. Doing so will dramatically increase the tickerplant ability to process records, from approximately 4.5 million records per second per core to up to 10 million. Bundling up you data in this way will reduce the CPU usage of the tickerplant and provide a first level of protection from failure. Setting the -t flag with a specified number of milliseconds will instruct the tickerplant to send batches at that frequency.

If you choose to run your tickerplant/chained tickerplant in batch mode, this adds in broadcasting. Broadcasting makes uses of the q internal function '-25!'. When data is serialised for TCP-based IPCs, it is converted into byte format, sent, then translated from byte format.
When the tp runs in zero-latency, this process is carried out for each individual message. When running in batch mode, -25! is used to serialize the full message batch once, then send it to each subscriber, rather than serialise each component of the batch and send it, for each subscriber.

Setting up an additional chained tickerplant, set up to subscribe to the tickerplant, that your RDB/other tickerplant subscribers can switch to, will insulate your tickerplant against the possibility that the increase in data throughput will result in subscribed process becoming slow subscribers, due to how efficiently they are able to process data. This will shift any build up of messages to the chained tickerplant and give you more time to deal with this before tickerplant failure. It is important to note that this is only appropriate for subscribers that do not need immediate access to the data, as introduction of a chained tickerplant would also introduce latency.

Another failure point in your system would be the RDB due to the fact that as throughput increase it will risk holding onto too much data in memory. As you're expecting the data increase to be tied to specific EUR syms that are fed into your system, you could add an additional RDB to your setup. Subscribing each RDB to a different subset of syms would balance out the load, and reduce the amount data held individually by each RDB. Also, depending on your data sources it may be feasable to situate a chained tickerplant in an EU datacentre. This will cut down on the latency between you and the datasource, which means messages will be processed faster by your system.

Tying in to this, you could add a gateway process that would allow you to bridge the two RDBs together so you can query both for data 'simultaneously' (Or just aj on data called from both ports).

As an alternative/additional option you could set up a writedown database or WDB to handle the end of day write down performed by the RDB. This would allow you to change the writedown frequency, such that you are saving down data to disk, and more importantly flushing your RDB(s) more regularly. The use of a WDB in this situation would mean that the RDB would not be involved in the disruptive writedown process (during which it is normally not able to be queried). And hence more regular writedowns would not affect intraday functionality in the RDB. You can have a look at the TorQ (tick framework) setup of a WDB below for an example of implementation:

https://github.com/AquaQAnalytics/TorQ/blob/master/code/processes/wdb.q

In regards to disaster recovery, having a secondary tickerplant set up that can be defaulted to if the main tickerplant fails is the main thing. Processes such as the RDB can be restarted with only temporary loss of functionality, and no permanent data loss, but it is a priority to keep the tickerplant (or a tickerplant running). An automatic discovery service to move subscribers to the tickerplant across to the backup tickerplant in case of failure would reduce the time taken in recovery. Having this backup tickerplant set up and running in Hot-Hot configuration would allow for fastest switch over, although this would come at a cost. 

Hope these suggestions give you an idea of how to deal with this issue,

Thanks,

Joseph.
